apiVersion: apps/v1
kind: Deployment
metadata:
  name: middle
  labels:
    app: middle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: middle
  template:
    metadata:
      labels:
        app: middle
    spec:
      containers:
      - name: middle
        image: zhllzh2936/last
        ports:
          - containerPort: 50051

---

apiVersion: v1
kind: Service
metadata:
  name: middle
  labels:
    app: middle
spec:
  type: NodePort
  ports:
    - nodePort: 32222
      port: 8080
      protocol: TCP
  selector:
    app: middle

